# Generated by Django 5.2.11 on 2026-05-21 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Character Name')),
                ('score', models.IntegerField(default=0, verbose_name='Score Points')),
                ('tier', models.CharField(choices=[('S', 'Alpha / En İyi'), ('A', 'Premium Katman'), ('B', 'Orta Seviye'), ('C', 'Standart / Sıradan'), ('D', 'Göz Ardı Edilenler')], default='C', max_length=1, verbose_name='Tier Level')),
                ('description', models.TextField(blank=True, verbose_name='Character Analysis')),
                ('pic_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Codex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, unique=True, verbose_name='Term')),
                ('definition', models.TextField(verbose_name='Definition')),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Codices',
            },
        ),
        migrations.CreateModel(
            name='CharacterSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Suggested Character Name')),
                ('reason', models.TextField(verbose_name='Reason for Suggestion')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Suggested By')),
            ],
            options={
                'verbose_name': 'Character Suggestion',
                'verbose_name_plural': 'Character Suggestions',
            },
        ),
        migrations.CreateModel(
            name='CodexSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100, verbose_name='Suggested Term')),
                ('definition', models.TextField(verbose_name='Suggested Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Suggested By')),
            ],
            options={
                'verbose_name': 'Codex Suggestion',
                'verbose_name_plural': 'Codex Suggestions',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibe.character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Vote',
                'verbose_name_plural': 'User Votes',
                'unique_together': {('user', 'character')},
            },
        ),
    ]
